import { useState, useEffect, useRef, useMemo } from "react"
import { AppIcon } from "@/components/ui/icon"
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip"
import { cn } from "@/lib/utils"
import type { KeyValuePair } from "@/types/request"
import { createKeyValuePair } from "@/types/request"
import { useI18n } from "@/hooks/useI18n"
import { useUIStore } from "@/stores/uiStore"
import { applyPlaceholderKeyChange, ensureTrailingKeyValuePlaceholder } from "@/lib/keyValueRows"

interface AutoGeneratedHeaderItem {
  key: string
  value: string
  enabled?: boolean
  description?: string
  tipTitle?: string
  tipContent?: string
  tipSettingHint?: string
}

interface KeyValueEditorProps {
  items: KeyValuePair[]
  onChange: (items: KeyValuePair[]) => void
  keyPlaceholder?: string
  valuePlaceholder?: string
  showDescription?: boolean
  supportFile?: boolean
  autoGeneratedItems?: AutoGeneratedHeaderItem[]
  hideAutoGeneratedByDefault?: boolean
  onToggleAutoGeneratedItem?: (key: string, enabled: boolean) => void
}

function parseBulkText(text: string): KeyValuePair[] {
  return text
    .split("\n")
    .filter((line) => line.trim())
    .map((line) => {
      const colonIdx = line.indexOf(":")
      if (colonIdx === -1) {
        return createKeyValuePair({ key: line.trim(), value: "" })
      }
      const key = line.slice(0, colonIdx).trim()
      const value = line.slice(colonIdx + 1).trim()
      return createKeyValuePair({ key, value })
    })
}

function serializeBulkText(items: KeyValuePair[]): string {
  return items
    .filter((item) => item.key)
    .map((item) => `${item.key}: ${item.value}`)
    .join("\n")
}

export function KeyValueEditor({
  items,
  onChange,
  keyPlaceholder = "Key",
  valuePlaceholder = "Value",
  showDescription = true,
  supportFile = false,
  autoGeneratedItems = [],
  hideAutoGeneratedByDefault = true,
  onToggleAutoGeneratedItem,
}: KeyValueEditorProps) {
  const { t } = useI18n()
  const layoutDirection = useUIStore((s) => s.layoutDirection)
  const [bulkMode, setBulkMode] = useState(false)
  const [bulkText, setBulkText] = useState("")
  const [hideAutoGenerated, setHideAutoGenerated] = useState(hideAutoGeneratedByDefault)
  const newKeyRef = useRef<HTMLInputElement>(null)
  const hiddenAutoGeneratedCount = hideAutoGenerated ? autoGeneratedItems.length : 0
  const isHorizontalLayout = layoutDirection === "horizontal"
  const displayItems = useMemo(() => ensureTrailingKeyValuePlaceholder(items, createKeyValuePair), [items])
  const tableMetrics = useMemo(() => {
    if (showDescription) {
      return isHorizontalLayout
        ? { minWidth: 700, keyWidth: "26%", valueWidth: "34%", descriptionWidth: "28%" }
        : { minWidth: 760, keyWidth: "24%", valueWidth: "40%", descriptionWidth: "24%" }
    }
    return isHorizontalLayout
      ? { minWidth: 600, keyWidth: "34%", valueWidth: "54%", descriptionWidth: "0%" }
      : { minWidth: 620, keyWidth: "34%", valueWidth: "54%", descriptionWidth: "0%" }
  }, [isHorizontalLayout, showDescription])

  const handleSendShortcut = (event: React.KeyboardEvent<HTMLElement>) => {
    if (event.key !== "Enter") return
    if (!(event.metaKey || event.ctrlKey) || event.altKey) return

    event.preventDefault()
    event.stopPropagation()
    window.dispatchEvent(new CustomEvent("minipost:send"))
  }

  useEffect(() => {
    setHideAutoGenerated(hideAutoGeneratedByDefault)
  }, [hideAutoGeneratedByDefault])

  const handleUpdate = (id: string, field: keyof KeyValuePair, value: string | boolean) => {
    const updated = items.map((item) => (item.id === id ? { ...item, [field]: value } : item))
    onChange(updated)
  }

  const handleDelete = (id: string) => {
    onChange(items.filter((item) => item.id !== id))
  }

  // 当用户在最后一行空行的 key 输入框聚焦 / 输入时，添加新行
  const handleNewRowKeyChange = (id: string, value: string) => {
    onChange(applyPlaceholderKeyChange(items, id, value, createKeyValuePair))
  }

  const enterBulkMode = () => {
    setBulkText(serializeBulkText(items))
    setBulkMode(true)
  }

  const exitBulkMode = () => {
    const parsed = parseBulkText(bulkText)
    if (parsed.length === 0 || parsed[parsed.length - 1].key !== "") {
      parsed.push(createKeyValuePair())
    }
    onChange(parsed)
    setBulkMode(false)
  }

  if (bulkMode) {
    return (
      <div className="p-[var(--size-padding-sm)]" onKeyDownCapture={handleSendShortcut}>
        <div className="flex items-center justify-between mb-2">
          <span className="text-[10px] text-[var(--fg-muted)]">
            {t("每行一条，格式：key: value（兼容 Chrome 复制的带空格格式）", "One item per line, format: key: value (compatible with Chrome copied format).")}
          </span>
          <button
            className="text-[10px] text-[var(--accent)] hover:text-[var(--accent-hover)] transition-colors"
            onClick={exitBulkMode}
          >
            {t("退出批量编辑", "Exit bulk edit")}
          </button>
        </div>
        <textarea
          value={bulkText}
          onChange={(e) => setBulkText(e.target.value)}
          className={cn(
            "w-full min-h-[200px] p-3 rounded-[var(--radius-input)]",
            "border border-[var(--border-color)] bg-[var(--surface)]",
            "text-[var(--fg)] font-mono text-[11px]",
            "placeholder:text-[var(--fg-muted)] resize-y",
            "focus:outline-none focus:border-[var(--accent)]"
          )}
          placeholder={"Content-Type: application/json\nAuthorization: Bearer token"}
          autoFocus
        />
      </div>
    )
  }

  return (
    <div className="flex h-full min-h-0 flex-col px-[var(--size-padding-sm)] pt-2 pb-2" onKeyDownCapture={handleSendShortcut}>
      <div className="min-h-0 flex-1 overflow-auto">
        <table
          className="w-full table-fixed border-collapse"
          style={{ fontSize: "11px", minWidth: `${tableMetrics.minWidth}px` }}
        >
          <colgroup>
            <col style={{ width: "28px" }} />
            <col style={{ width: tableMetrics.keyWidth }} />
            <col style={{ width: tableMetrics.valueWidth }} />
            {showDescription && <col style={{ width: tableMetrics.descriptionWidth }} />}
            <col style={{ width: "64px" }} />
          </colgroup>
          <thead className="sticky top-0 z-[1] bg-[var(--surface)]">
          <tr>
            <th className="w-7 border border-[var(--border-color)] px-1 py-1" />
            <th className="select-text text-left border border-[var(--border-color)] px-2 py-1 font-semibold text-[var(--fg-secondary)]">
              <div className="flex min-w-0 items-center justify-between gap-2">
                <span className="min-w-0 truncate whitespace-nowrap">{keyPlaceholder}</span>
                {autoGeneratedItems.length > 0 && (
                  <button
                    type="button"
                    className={cn(
                      "inline-flex h-[16px] min-w-[72px] shrink-0 items-center justify-center gap-1 rounded-full border px-1.5 text-[10px] font-medium transition-colors",
                      "border-[var(--border-color)] bg-[var(--surface-secondary)] text-[var(--fg-secondary)] hover:text-[var(--fg)]"
                    )}
                    onClick={() => setHideAutoGenerated((prev) => !prev)}
                  >
                    <AppIcon name={hideAutoGenerated ? "eye" : "viewOff"} size={10} />
                    {hideAutoGenerated
                      ? hiddenAutoGeneratedCount > 0
                        ? `${t("显示", "Show")} ${hiddenAutoGeneratedCount}`
                        : t("显示", "Show")
                      : t("隐藏", "Hide")}
                  </button>
                )}
              </div>
            </th>
            <th className="select-text text-left border border-[var(--border-color)] px-2 py-1 font-semibold text-[var(--fg-secondary)]">{valuePlaceholder}</th>
            {showDescription && (
              <th className="select-text text-left border border-[var(--border-color)] px-2 py-1 font-semibold text-[var(--fg-secondary)]">
                {t("说明", "Description")}
              </th>
            )}
            <th className="w-16 border border-[var(--border-color)] px-1 py-1 text-right">
              <button
                className="text-[10px] text-[var(--fg-muted)] hover:text-[var(--accent)] transition-colors whitespace-nowrap"
                onClick={enterBulkMode}
              >
                {t("批量编辑", "Bulk Edit")}
              </button>
            </th>
          </tr>
          </thead>
          <tbody>
          {!hideAutoGenerated && autoGeneratedItems.map((item, idx) => (
            <tr
              key={`auto-${item.key}-${idx}`}
              className="bg-[var(--surface-secondary)]/40"
            >
              <td className="border border-[var(--border-color)] px-1 py-0 text-center">
                <input
                  type="checkbox"
                  checked={item.enabled ?? true}
                  onChange={(event) => onToggleAutoGeneratedItem?.(item.key, event.target.checked)}
                  disabled={!onToggleAutoGeneratedItem}
                  className={cn(
                    "w-3 h-3 rounded accent-[var(--accent)]",
                    onToggleAutoGeneratedItem ? "cursor-pointer" : "cursor-default opacity-60"
                  )}
                />
              </td>
              <td className="border border-[var(--border-color)] h-[24px] px-2 py-0">
                <div className="flex h-[24px] min-w-0 items-center justify-between gap-2">
                  <span title={item.key} className="min-w-0 flex-1 truncate font-mono text-[var(--fg-secondary)] select-text">
                    {item.key}
                  </span>
                  {item.tipContent && (
                    <Tooltip>
                      <TooltipTrigger asChild>
                        <button
                          type="button"
                          className="inline-flex h-4 w-4 shrink-0 items-center justify-center rounded-[4px] text-[var(--fg-muted)] hover:bg-[var(--button-bg)] hover:text-[var(--fg)]"
                          aria-label={`${t("说明", "Info")}: ${item.key}`}
                        >
                          <AppIcon name="info" size={12} />
                        </button>
                      </TooltipTrigger>
                      <TooltipContent side="right" className="max-w-[360px] px-3 py-2.5 text-[12px] leading-5">
                        {item.tipTitle && <div className="mb-1 text-[12px] font-semibold text-[var(--fg)]">{item.tipTitle}</div>}
                        <div className="text-[var(--fg-secondary)]">{item.tipContent}</div>
                        {item.tipSettingHint && (
                          <div className="mt-2 border-t border-[var(--border-subtle)] pt-2 text-[11px] text-[var(--fg-muted)]">
                            {item.tipSettingHint}
                          </div>
                        )}
                      </TooltipContent>
                    </Tooltip>
                  )}
                </div>
              </td>
              <td className="border border-[var(--border-color)] h-[24px] px-2 py-0">
                <span
                  title={item.value}
                  className="inline-flex h-[24px] min-w-0 max-w-full items-center overflow-hidden text-ellipsis whitespace-nowrap font-mono text-[var(--fg-muted)] select-text"
                >
                  {item.value}
                </span>
              </td>
              {showDescription && (
                <td className="border border-[var(--border-color)] h-[24px] px-2 py-0">
                  <span
                    title={item.description || t("发送时自动生成", "Auto-generated when sending")}
                    className="inline-flex h-[24px] min-w-0 max-w-full items-center overflow-hidden text-ellipsis whitespace-nowrap text-[var(--fg-muted)] select-text"
                  >
                    {item.description || t("发送时自动生成", "Auto-generated when sending")}
                  </span>
                </td>
              )}
              <td className="border border-[var(--border-color)] px-1 py-0" />
            </tr>
          ))}
          {displayItems.map((item, idx) => {
            const isLastEmpty = idx === displayItems.length - 1 && !item.key && !item.value
            return (
              <tr key={item.id} className="group hover:bg-[var(--surface-secondary)]/50 transition-colors">
                <td className="border border-[var(--border-color)] px-1 py-0 text-center">
                  <input
                    type="checkbox"
                    checked={item.enabled}
                    onChange={(e) => handleUpdate(item.id, "enabled", e.target.checked)}
                    className="w-3 h-3 rounded accent-[var(--accent)] cursor-pointer"
                    disabled={isLastEmpty}
                    style={isLastEmpty ? { opacity: 0.3 } : {}}
                  />
                </td>
                <td className="border border-[var(--border-color)] px-0 py-0">
                  <input
                    ref={isLastEmpty ? newKeyRef : undefined}
                    value={item.key}
                    onChange={(e) => {
                      if (isLastEmpty) {
                        handleNewRowKeyChange(item.id, e.target.value)
                      } else {
                        handleUpdate(item.id, "key", e.target.value)
                      }
                    }}
                    placeholder={keyPlaceholder}
                    className={cn(
                      "w-full h-[24px] px-2 bg-transparent text-[var(--fg)] font-mono select-text",
                      "text-[11px] placeholder:text-[var(--fg-muted)] placeholder:italic",
                      "focus:outline-none",
                      !item.enabled && !isLastEmpty && "opacity-40"
                    )}
                  />
                </td>
                <td className="border border-[var(--border-color)] px-0 py-0">
                  <input
                    value={item.value}
                    onChange={(e) => handleUpdate(item.id, "value", e.target.value)}
                    placeholder={valuePlaceholder}
                    className={cn(
                      "w-full h-[24px] px-2 bg-transparent text-[var(--fg)] font-mono select-text",
                      "text-[11px] placeholder:text-[var(--fg-muted)] placeholder:italic",
                      "focus:outline-none",
                      !item.enabled && !isLastEmpty && "opacity-40"
                    )}
                    disabled={isLastEmpty}
                  />
                </td>
                {showDescription && (
                  <td className="border border-[var(--border-color)] px-0 py-0">
                    <input
                      value={item.description ?? ""}
                      onChange={(e) => handleUpdate(item.id, "description", e.target.value)}
                      placeholder={t("说明", "Description")}
                      className={cn(
                        "w-full h-[24px] px-2 bg-transparent text-[var(--fg-secondary)] select-text",
                        "text-[11px] placeholder:text-[var(--fg-muted)] placeholder:italic",
                        "focus:outline-none",
                        !item.enabled && !isLastEmpty && "opacity-40"
                      )}
                      disabled={isLastEmpty}
                    />
                  </td>
                )}
                <td className="border border-[var(--border-color)] px-1 py-0 text-center">
                  {!isLastEmpty && (
                    <button
                      className="h-4 w-4 inline-flex items-center justify-center rounded-[2px] opacity-0 group-hover:opacity-100 hover:bg-[var(--sidebar-hover)] text-[var(--fg-muted)] hover:text-[var(--danger)] transition-all"
                      onClick={() => handleDelete(item.id)}
                    >
                      <AppIcon name="delete" size={10} />
                    </button>
                  )}
                </td>
              </tr>
            )
          })}
          </tbody>
        </table>
      </div>
    </div>
  )
}
