// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory(arg1) {
  return window['go']['main']['App']['ClearHistory'](arg1);
}

export function CreateBackup() {
  return window['go']['main']['App']['CreateBackup']();
}

export function CreateEnvironment(arg1, arg2) {
  return window['go']['main']['App']['CreateEnvironment'](arg1, arg2);
}

export function CreateFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2, arg3);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateRequestItem(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateRequestItem'](arg1, arg2, arg3);
}

export function DeleteEnvironment(arg1, arg2) {
  return window['go']['main']['App']['DeleteEnvironment'](arg1, arg2);
}

export function DeleteFolder(arg1, arg2) {
  return window['go']['main']['App']['DeleteFolder'](arg1, arg2);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteRequestItem(arg1, arg2) {
  return window['go']['main']['App']['DeleteRequestItem'](arg1, arg2);
}

export function DuplicateFolder(arg1, arg2) {
  return window['go']['main']['App']['DuplicateFolder'](arg1, arg2);
}

export function DuplicateRequest(arg1, arg2) {
  return window['go']['main']['App']['DuplicateRequest'](arg1, arg2);
}

export function ExportProjectJSON(arg1) {
  return window['go']['main']['App']['ExportProjectJSON'](arg1);
}

export function GetCollectionData(arg1) {
  return window['go']['main']['App']['GetCollectionData'](arg1);
}

export function GetHistory(arg1) {
  return window['go']['main']['App']['GetHistory'](arg1);
}

export function ImportCollectionWithStrategy(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ImportCollectionWithStrategy'](arg1, arg2, arg3, arg4, arg5);
}

export function ImportCurl(arg1) {
  return window['go']['main']['App']['ImportCurl'](arg1);
}

export function ImportFromFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportFromFile'](arg1, arg2, arg3);
}

export function ImportFromURL(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportFromURL'](arg1, arg2, arg3);
}

export function ImportPostmanCollection(arg1, arg2) {
  return window['go']['main']['App']['ImportPostmanCollection'](arg1, arg2);
}

export function ImportPostmanEnvironment(arg1, arg2) {
  return window['go']['main']['App']['ImportPostmanEnvironment'](arg1, arg2);
}

export function ImportSwagger(arg1, arg2) {
  return window['go']['main']['App']['ImportSwagger'](arg1, arg2);
}

export function ListEnvironments(arg1) {
  return window['go']['main']['App']['ListEnvironments'](arg1);
}

export function ListFolders(arg1) {
  return window['go']['main']['App']['ListFolders'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListRequests(arg1) {
  return window['go']['main']['App']['ListRequests'](arg1);
}

export function MoveCollectionNode(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['MoveCollectionNode'](arg1, arg2, arg3, arg4, arg5);
}

export function MoveFolder(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MoveFolder'](arg1, arg2, arg3, arg4);
}

export function MoveRequestItem(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MoveRequestItem'](arg1, arg2, arg3, arg4);
}

export function OpenFileDialogAny() {
  return window['go']['main']['App']['OpenFileDialogAny']();
}

export function OpenFileDialogJSON() {
  return window['go']['main']['App']['OpenFileDialogJSON']();
}

export function PreviewImportFromFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['PreviewImportFromFile'](arg1, arg2, arg3);
}

export function PreviewImportFromURL(arg1, arg2, arg3) {
  return window['go']['main']['App']['PreviewImportFromURL'](arg1, arg2, arg3);
}

export function RenameFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameFolder'](arg1, arg2, arg3);
}

export function RenameProject(arg1, arg2) {
  return window['go']['main']['App']['RenameProject'](arg1, arg2);
}

export function RenameRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameRequest'](arg1, arg2, arg3);
}

export function RestoreBackup(arg1) {
  return window['go']['main']['App']['RestoreBackup'](arg1);
}

export function SaveEnvironment(arg1) {
  return window['go']['main']['App']['SaveEnvironment'](arg1);
}

export function SaveFileDialogJSON(arg1, arg2) {
  return window['go']['main']['App']['SaveFileDialogJSON'](arg1, arg2);
}

export function SaveRequestItem(arg1) {
  return window['go']['main']['App']['SaveRequestItem'](arg1);
}

export function SaveResponseToFile(arg1, arg2) {
  return window['go']['main']['App']['SaveResponseToFile'](arg1, arg2);
}

export function SaveTextFile(arg1, arg2) {
  return window['go']['main']['App']['SaveTextFile'](arg1, arg2);
}

export function SendRequest(arg1) {
  return window['go']['main']['App']['SendRequest'](arg1);
}

export function SendRequestWithEnv(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendRequestWithEnv'](arg1, arg2, arg3);
}

export function SendRequestWithEnvStream(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendRequestWithEnvStream'](arg1, arg2, arg3, arg4);
}

export function UpdateProjectDescription(arg1, arg2) {
  return window['go']['main']['App']['UpdateProjectDescription'](arg1, arg2);
}

export function UpdateProjectTheme(arg1, arg2) {
  return window['go']['main']['App']['UpdateProjectTheme'](arg1, arg2);
}
