// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function ClearHistory(arg1:string):Promise<void>;

export function CreateEnvironment(arg1:string,arg2:string):Promise<model.Environment>;

export function CreateFolder(arg1:string,arg2:string,arg3:string):Promise<model.Folder>;

export function CreateProject(arg1:string):Promise<model.Project>;

export function CreateRequestItem(arg1:string,arg2:string,arg3:string):Promise<model.RequestItem>;

export function DeleteEnvironment(arg1:string,arg2:string):Promise<void>;

export function DeleteFolder(arg1:string,arg2:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteRequestItem(arg1:string,arg2:string):Promise<void>;

export function GetHistory(arg1:string):Promise<Array<model.HistoryEntry>>;

export function ImportCurl(arg1:string):Promise<model.SendRequestInput>;

export function ListEnvironments(arg1:string):Promise<Array<model.Environment>>;

export function ListFolders(arg1:string):Promise<Array<model.Folder>>;

export function ListProjects():Promise<Array<model.Project>>;

export function ListRequests(arg1:string):Promise<Array<model.RequestItem>>;

export function RenameFolder(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RenameProject(arg1:string,arg2:string):Promise<model.Project>;

export function SaveEnvironment(arg1:model.Environment):Promise<void>;

export function SaveRequestItem(arg1:model.RequestItem):Promise<void>;

export function SendRequest(arg1:model.SendRequestInput):Promise<model.HttpResponse>;

export function SendRequestWithEnv(arg1:model.SendRequestInput,arg2:string,arg3:string):Promise<model.HttpResponse>;
