// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function ClearHistory(arg1:string):Promise<void>;

export function CreateBackup():Promise<string>;

export function CreateEnvironment(arg1:string,arg2:string):Promise<model.Environment>;

export function CreateFolder(arg1:string,arg2:string,arg3:string):Promise<model.Folder>;

export function CreateProject(arg1:string):Promise<model.Project>;

export function CreateRequestItem(arg1:string,arg2:string,arg3:string):Promise<model.RequestItem>;

export function DeleteEnvironment(arg1:string,arg2:string):Promise<void>;

export function DeleteFolder(arg1:string,arg2:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteRequestItem(arg1:string,arg2:string):Promise<void>;

export function DuplicateFolder(arg1:string,arg2:string):Promise<model.Folder>;

export function DuplicateRequest(arg1:string,arg2:string):Promise<model.RequestItem>;

export function ExportProjectJSON(arg1:string):Promise<string>;

export function GetCollectionData(arg1:string):Promise<model.CollectionData>;

export function GetHistory(arg1:string):Promise<Array<model.HistoryEntry>>;

export function ImportCurl(arg1:string):Promise<model.SendRequestInput>;

export function ImportFromFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ImportPostmanCollection(arg1:string,arg2:string):Promise<void>;

export function ImportSwagger(arg1:string,arg2:string):Promise<void>;

export function ListEnvironments(arg1:string):Promise<Array<model.Environment>>;

export function ListFolders(arg1:string):Promise<Array<model.Folder>>;

export function ListProjects():Promise<Array<model.Project>>;

export function ListRequests(arg1:string):Promise<Array<model.RequestItem>>;

export function MoveCollectionNode(arg1:string,arg2:string,arg3:model.CollectionNodeType,arg4:string,arg5:number):Promise<void>;

export function MoveFolder(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function MoveRequestItem(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function OpenFileDialogAny():Promise<string>;

export function OpenFileDialogJSON():Promise<string>;

export function RenameFolder(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RenameProject(arg1:string,arg2:string):Promise<model.Project>;

export function RenameRequest(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RestoreBackup(arg1:string):Promise<void>;

export function SaveEnvironment(arg1:model.Environment):Promise<void>;

export function SaveFileDialogJSON(arg1:string,arg2:string):Promise<void>;

export function SaveRequestItem(arg1:model.RequestItem):Promise<void>;

export function SaveResponseToFile(arg1:string,arg2:string):Promise<void>;

export function SaveTextFile(arg1:string,arg2:string):Promise<void>;

export function SendRequest(arg1:model.SendRequestInput):Promise<model.HttpResponse>;

export function SendRequestWithEnv(arg1:model.SendRequestInput,arg2:string,arg3:string):Promise<model.HttpResponse>;

export function UpdateProjectDescription(arg1:string,arg2:string):Promise<model.Project>;

export function UpdateProjectTheme(arg1:string,arg2:string):Promise<model.Project>;
